config/routes.rb
Rails.application.routes.draw do
  get 'admins/admin_view'

  resources :universities do

resources :students

end

  devise_for :users

   root 'admins#admin_view'

end

app/models/student.rb
class Student < ActiveRecord::Base

	belongs_to :university

	  has_attached_file :photo
	 do_not_validate_attachment_file_type :photo

   validates_uniqueness_of :sid, :message => "already exists"

end

app/models/university.rb
class University < ActiveRecord::Base
	has_many :students

   validates_uniqueness_of :uid, :message => "already exists"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

	before_action :authenticate_user!
  def admin_view
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

before_action :authenticate_user!
	 def create
    @university = University.find(params[:university_id])
    @student = @university.students.create(student_params)
    redirect_to university_path(@university)
  end
 
 def destroy
    @university = University.find(params[:university_id])
    @student = @university.students.find(params[:id])
    @student.destroy
    redirect_to university_path(@university)
  end

  private
    def student_params
      params.require(:student).permit(:sid, :name, :age, :photo)
    end
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController

	before_action :authenticate_user!

def index
  @university = University.all
end

def new

	@university = University.new
	
end

def show

	 @university = University.find(params[:id])
	
end

def create

	 @university = University.new(university_params)
 
  if @university.save
  redirect_to @university
  else
    render 'new'
  end

	
end

def edit
  @university = University.find(params[:id])
end

def update
  @university = University.find(params[:id])
 
  if @university.update(university_params)
    redirect_to @university
  else
    render 'edit'
  end
end

def destroy
  @university = University.find(params[:id])
  @university.destroy
 
  redirect_to universities_path
end
private
  def university_params
    params.require(:university).permit(:uid, :name, :location)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/admins/admin_view.html.erb
<div class="container">
<div class="jumbotron">
   
  

  <% if current_user.present? %>
  <p>Welcome <%= current_user.email %></p>
  
  <button type="button" class="btn btn-default" >
  
  	<%= link_to 'Log Out', destroy_user_session_path, :method => :delete %>
  </button>
  
  <button type="button" class="btn btn-default" >
   <%= link_to 'My Universities Data', controller: 'universities' %>

</button>

<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

  
</div></div>



 
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UniCms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for @student, :html => { :class => "form-horizontal student" } do |f| %>

    <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :sid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sid, :class => 'form-control' %>
    </div>
    <%= error_span(@student[:sid]) %>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@student[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :age, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%= error_span(@student[:age]) %>
  </div>
  <div class="control-group">
    <%= f.label :photo_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :photo_file_name, :class => 'form-control' %>
    </div>
    <%= error_span(@student[:photo_file_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :photo_content_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :photo_content_type, :class => 'form-control' %>
    </div>
    <%= error_span(@student[:photo_content_type]) %>
  </div>
  <div class="control-group">
    <%= f.label :photo_file_size, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :photo_file_size, :class => 'form-control' %>
    </div>
    <%= error_span(@student[:photo_file_size]) %>
  </div>
  <div class="control-group">
    <%= f.label :photo_updated_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :photo_updated_at, :class => 'form-control' %>
    </div>
    <%= error_span(@student[:photo_updated_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :universities_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :universities_id, :class => 'form-control' %>
    </div>
    <%= error_span(@student[:universities_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :university_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :university_id, :class => 'form-control' %>
    </div>
    <%= error_span(@student[:university_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            students_path, :class => 'btn btn-default' %>

<% end %>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:sid) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:photo_file_name) %></th>
      <th><%= model_class.human_attribute_name(:photo_content_type) %></th>
      <th><%= model_class.human_attribute_name(:photo_file_size) %></th>
      <th><%= model_class.human_attribute_name(:photo_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:universities_id) %></th>
      <th><%= model_class.human_attribute_name(:university_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students  do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.sid %></td>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><%= student.photo_file_name %></td>
        <td><%= student.photo_content_type %></td>
        <td><%= student.photo_file_size %></td>
        <td><%= student.photo_updated_at %></td>
        <td><%= student.universities_id %></td>
        <td><%= student.university_id %></td>
        <td><%=l student.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:sid) %>:</strong></dt>
  <dd><%= @student.sid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @student.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @student.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:photo_file_name) %>:</strong></dt>
  <dd><%= @student.photo_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:photo_content_type) %>:</strong></dt>
  <dd><%= @student.photo_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:photo_file_size) %>:</strong></dt>
  <dd><%= @student.photo_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:photo_updated_at) %>:</strong></dt>
  <dd><%= @student.photo_updated_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:universities_id) %>:</strong></dt>
  <dd><%= @student.universities_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:university_id) %>:</strong></dt>
  <dd><%= @student.university_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/universities/_form.html.erb
<%= form_for @university, :html => { :class => "form-horizontal university" } do |f| %>

    <% if @university.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@university.errors.count, "error") %> prohibited this university from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @university.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :uid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :uid, :class => 'form-control' %>
    </div>
    <%= error_span(@university[:uid]) %>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@university[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%= error_span(@university[:location]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            universities_path, :class => 'btn btn-default' %>

<% end %>

app/views/universities/edit.html.erb
<%- model_class = University -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/universities/index.html.erb
<div class="container">
<div class="jumbotron">
   
 <h1>   Listing Available Universities</h1>
  
</div>

<%- model_class = University -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:uid) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @university.each do |university| %>
      <tr>
        <td><%= university.id %></td>
        <td><%= university.uid %></td>
        <td><%= link_to  university.name, university_path(university) %></td>
        <td><%= university.location %></td>
        <td><%=l university.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_university_path(university), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      university_path(university),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_university_path,
            :class => 'btn btn-primary' %>

            <%= link_to t('/', :default => t("helpers.links.back")),
             admins_admin_view_path,
            :class => 'btn btn-primary' %>

</div>

app/views/universities/new.html.erb
<%- model_class = University -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/universities/show.html.erb
<div class="container">
<div class="jumbotron">
   
  <p>



<%- model_class = University -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:uid) %>:</strong></dt>
  <dd><%= @university.uid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @university.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @university.location %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              universities_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_university_path(@university), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              university_path(@university),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %> 

              </p>
</div>
<hr/>


<hr/>


 

<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:sid) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:photo_file_name) %></th>
       <th>Actions</th>
        
    </tr>
  </thead>
  <tbody>
    <% @university.students.each do |student| %>
      <tr>
        <td><%= student.id  %></td>
        <td><%= student.sid %></td>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><img width=70px height=50px src=" <%=student.photo.url %>"/></td> 
          
           <td type="button" class="btn btn-default" style="margin:5px"> 
         <%= link_to 'Delete Record', [student.university, student],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
        </td>
   
  
      </tr>
    <% end %>
  </tbody>
</table>
 


 

<h2>Add a Student:</h2>

 <div class="col-sm-4">

<%= form_for([@university, @university.students.build], :html => { :multipart => true }, :class => "form-horizontal", :role => "form") do |f|  
 %>
  <p class="form-group">
    <%= f.label :Student_ID %><br>
    <%= f.text_field :sid , :class => "form-control"%>
  </p>
  <p class="form-group">
    <%= f.label :Student_Name %><br>
    <%= f.text_area :name , :class => "form-control"%>
  </p>

  <p class="form-group"> 
    <%= f.label :Student_Age %><br>
    <%= f.text_area :age  , :class => "form-control"%>
  </p>

  <p class="form-group">
    <%= f.label :Student_Photo %><br>
    <%= f.file_field :photo , :class => "form-control"%>

  </p>
 <button type="submit" class="btn btn-default">Create </button> 
     
  
<% end %>

   </div>
</div>